name: Share Artifacts and Cache Example
run-name: Reuse Artifacts Example

on:
  push:
    branches:
      - main

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create artifact
        run: echo "Hello from Job 1" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-artifact
          path: artifact.txt

  use-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: example-artifact

      - name: Use artifact
        run: cat artifact.txt