name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

# jobs:
#   first-tf-job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
      
#       - name: Set up AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.10.3 # Replace with the version you're using

#       - name: Initialize Terraform
#         run: terraform init

#       - name: Validate Terraform
#         run: terraform validate

#       - name: Plan Terraform
#         run: terraform plan

#       - name: Apply Terraform
#         if: github.ref == 'refs/heads/main' # only run when changes are pushed to main branch
#         run: terraform apply -auto-approve

jobs:
  init:
    name: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

  wait_for_approval:
    name: Wait for Approval
    needs: init
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Pause for Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: maximillianus
          minimum-approvals: 1
          issue-title: "Testing manual approval"
          issue-body: |
            Please approve or deny. 
            Approval Keywords: approve, approved, lgtm, yes. 
            Denial Keywords: deny, denied, no

  plan:
    name: Plan Terraform Resources
    needs: wait_for_approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan
      
