name: Terraform CI/CD with Environment as manual approval
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan:
    name: terraform plan
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan  # Persist the tfplan file as an artifact
  apply:
    name: terraform apply
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: release  # Use a GitHub Environment for approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download tfplan artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan  # Retrieve the tfplan file artifact

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan